# Generated by Django 2.2.1 on 2019-05-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190513_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='positions_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Positions'),
        ),
    ]
