# Generated by Django 2.2.1 on 2019-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190515_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='shift_types',
            name='shift_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shift_types',
            name='shift_start',
            field=models.TimeField(null=True),
        ),
    ]
