# Generated by Django 2.2.1 on 2019-05-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190517_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifts',
            old_name='date',
            new_name='date_end',
        ),
        migrations.AddField(
            model_name='shifts',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='shift_types',
            name='shift_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift_types',
            name='shift_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='task',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
